name: build_ubuntu

on:
  push:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile.debian
      - .github/workflows/build_ubuntu.yml
  pull_request:
    branches:
      - master
    paths:
      - user-entrypoint.sh
      - Dockerfile.debian
      - .github/workflows/build_ubuntu.yml
  repository_dispatch:
    types:
      - ubuntu_image_update

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TITLE: User Ubuntu
    strategy:
      matrix:
        include:
          - base-image: ubuntu:18.04
            dockerfile: Dockerfile.debian
            tags: |-
              ghcr.io/phasecorex/user-ubuntu:18.04
              ghcr.io/phasecorex/user-ubuntu:bionic
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
          - base-image: ubuntu:20.04
            dockerfile: Dockerfile.debian
            tags: |-
              ghcr.io/phasecorex/user-ubuntu:20.04
              ghcr.io/phasecorex/user-ubuntu:focal
              ghcr.io/phasecorex/user-ubuntu:latest
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/ppc64le
              linux/s390x
          - base-image: ubuntu:14.04
            dockerfile: Dockerfile.debian
            tags: |-
              ghcr.io/phasecorex/user-ubuntu:14.04
              ghcr.io/phasecorex/user-ubuntu:trusty
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
          - base-image: ubuntu:16.04
            dockerfile: Dockerfile.debian
            tags: |-
              ghcr.io/phasecorex/user-ubuntu:16.04
              ghcr.io/phasecorex/user-ubuntu:xenial
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
              linux/386
              linux/ppc64le
              linux/s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push ${{ matrix.base-image }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
          cache-from: ${{ matrix.tags }}
          build-args: |
            BASE_IMG=${{ matrix.base-image }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.title=${{ env.TITLE }}
            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
